swagger: "2.0"
info:
  title: DevJobs API 🗒️
  description: API for managing dev jobs
  version: 1.0.0
schemes:
  - http
paths:
  /jobs/6/2:
    get:
      summary: Retrieve a list of all ToDo items.
      description: Returns an array of ToDo items stored in the database. Each item includes a unique ID, a description of the task (`todoTask`), and a boolean value (`done`) indicating whether the task is completed or not.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                  required: true
                  example: 1
                company:
                  type: string
                  required: true
                  example: Scoot
                logo:
                  type: string
                  required: true
                  example: /iamges/scoot.svg
                logoBackground:
                  type: string
                  required: true
                  example: hsl(36, 87%, 49%)
                position:
                  type: string
                  required: true
                  example: Senior Software Engineer
                postedAt:
                  type: string
                  required: true
                  example: 5h ago
                contract:
                  type: string
                  required: true
                  example: Full Time
                location:
                  type: string
                  required: true
                  example: United States
                website:
                  type: string
                  required: true
                  example: https://www.flyscoot.com/en/
                apply:
                  type: string
                  required: true
                  example: https://www.flyscoot.com/en/
                description:
                  type: string
                  required: true
                  example: Scoot is looking for job
                requirements:
                  content:
                    type: string
                    required: true
                    example: The ideal candidate is as passionate about solving challenges through …
                  items:
                    - type: string
                      required: true
                role:
                  content:
                    type: string
                    required: true
                    example: "/iamges/scoot.svg"
                  items:
                    - type: string
                      required: true
                      example: "/iamges/scoot.svg"
